INSERT INTO `AdUCPEResidences`.`pets` (`pet_type`, `breed`,`tenants_id`, `is_approved`)
VALUES
	('Dog', 'German Shepherd', 21, 1),
	('Dog', 'German Shepherd', 3, 1),
	('Dog', 'Husky', 22, 0),
	('Dog', 'Husky', 25, 0),
	('Dog', 'Husky', 28, 1),
	('Dog', 'Husky', 28, 1),
	('Dog', 'Husky', 28, 0),
	('Dog', 'Husky', 28, 0),
	('Dog', 'Husky', 28, 1),
	('Dog', 'Husky', 28, 1),
	('Dog', 'Husky', 35, 0),
	('Dog', 'Husky', 40, 1),
	('Dog', 'Husky', 36, 0),
	('Dog', 'Husky', 58, 1),
	('Dog', 'Husky', 58, 0),
	('Dog', 'Husky', 58, 0),
	('Dog', 'Husky', 65, 0),
	('Dog', 'Husky', 79, 1),
	('Dog', 'Husky', 80, 0),
	('Dog', 'Husky', 80, 0),
	('Dog', 'Husky', 95, 1),
	('Dog', 'Husky', 95, 0),
	('Dog', 'Pug', 34, 0),
	('Dog', 'Pug', 64, 1),
	('Dog', 'Pug', 71, 1),
	('Dog', 'Pug', 79, 0),
	('Dog', 'Pug', 80, 1),
	('Dog', 'Bulldog', 57, 0),
	('Dog', 'Bulldog', 57, 1),
	('Dog', 'Bulldog', 57, 1),
	('Dog', 'Bulldog', 57, 1),
	('Dog', 'Labrador', 37, 0),
	('Dog', 'Labrador', 37, 1),
	('Dog', 'Labrador', 25, 1),
	('Dog', 'Labrador', 30, 0),
	('Dog', 'Shih Tzu', 1, 1),
	('Dog', 'Shih Tzu', 5, 1),
	('Dog', 'Shih Tzu', 16, 0),
	('Dog', 'Shih Tzu', 19, 1),
	('Dog', 'Shih Tzu', 25, 0),
	('Dog', 'Shih Tzu', 23, 1),
	('Dog', 'Shih Tzu', 48, 0),
	('Dog', 'Shih Tzu', 50, 1),
	('Dog', 'Shih Tzu', 52, 0),
	('Dog', 'Shih Tzu', 59, 0),
	('Dog', 'Shih Tzu', 60, 1),
	('Dog', 'Chow Chow', 69, 1),
	('Dog', 'Chow Chow', 69, 1),
	('Dog', 'Japanese Spitz', 69, 1),
	('Dog', 'Pomsky', 69, 0),
	('Dog', 'Pomsky', 69, 1),
	('Dog', 'Beagle', 33, 1),
	('Dog', 'Golden Retriever', 99, 1),
	('Dog', 'Golden Retriever', 80, 0),
	('Dog', 'Golden Retriever', 70, 0),
	('Dog', 'Golden Retriever', 70, 1),
	('Dog', 'Golden Retriever', 70, 1),
	('Dog', 'Golden Retriever', 70, 0),
	('Dog', 'Golden Retriever', 70, 1),
	('Dog', 'Poodle', 68, 1),
	('Dog', 'Boxer', 7, 0),
	('Dog', 'Doberman', 81, 1),
	('Dog', 'Doberman', 81, 0),
	('Dog', 'Rottweiler', 78, 1),
	('Dog', 'Rottweiler', 43, 0),
	('Dog', 'Great Dane', 43, 1),
	('Dog', 'Rottweiler', 33, 0),
	('Dog', 'Corgi', 13, 1),
	('Dog', 'Corgi', 13, 0),
	('Dog', 'Corgi', 13, 1),
	('Dog', 'Corgi', 13, 0),
	('Dog', 'Corgi', 63, 1),
	('Dog', 'Corgi', 63, 0),
	('Bird', 'Parrot ', 1, 1),
	('Bird', 'Canary', 20, 0),
	('Bird', 'Cockatiel', 90, 1),
	('Bird', 'Lovebird', 19, 1),
	('Cat', 'Russian Blue', 70, 1),
	('Cat', 'Caucasian Blue', 70, 1),
	('Cat', 'Chinese Pink', 70, 1),
	('Cat', 'Persian Cat', 14, 0),
	('Cat', 'Persian Cat', 14, 1),
	('Cat', 'Scottish Fold', 44, 0),
	('Cat', 'British Shorthair', 38, 1),
	('Cat', 'British Relaxed', 38, 0),
	('Cat', 'British Longhair', 38, 0),
	('Cat', 'British Rebonded', 38, 1),
	('Cat', 'Munchkin ', 100, 1),
	('Cat', 'Tabby ', 32, 0),
	('Cat', 'Tabby ', 60, 1),
	('Cat', 'Tabby ', 5, 1),
	('Cat', 'Tabby ', 7, 0),
	('Cat', 'Tabby ', 3, 1),
	('Cat', 'Persian Cat ', 25, 1),
	('Cat', 'Alamid ', 25, 0),
	('Cat', 'Munchkin ', 25, 0),
	('Cat', 'Bavarian ', 25, 0),
	('Cat', 'Choco Butternut ', 25, 1),
	('Cat', 'Tabby ', 25, 0),
	('Cat', 'Siberian Cat ', 23, 0);
    
    