-- MySQL Script generated by MySQL Workbench
-- Sun Dec  9 16:48:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aducperesidences
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aducperesidences
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aducperesidences` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `aducperesidences` ;

-- -----------------------------------------------------
-- Table `aducperesidences`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aducperesidences`.`employees` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `middlename` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aducperesidences`.`tenants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aducperesidences`.`tenants` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `middlename` VARCHAR(100) NULL DEFAULT NULL,
  `unit_no` VARCHAR(45) NOT NULL,
  `phone_no` VARCHAR(45) NULL DEFAULT NULL,
  `email_address` VARCHAR(100) NULL DEFAULT NULL,
  `provincial_address` VARCHAR(100) NULL DEFAULT NULL,
  `move_in_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aducperesidences`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aducperesidences`.`pets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pet_type` VARCHAR(45) NOT NULL,
  `breed` VARCHAR(45) NOT NULL,
  `tenants_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `tenants_id`),
  INDEX `fk_pets_tenants1_idx` (`tenants_id` ASC) VISIBLE,
  CONSTRAINT `fk_pets_tenants1`
    FOREIGN KEY (`tenants_id`)
    REFERENCES `aducperesidences`.`tenants` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aducperesidences`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aducperesidences`.`services` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `service_type` VARCHAR(45) NOT NULL,
  `service_charge` DECIMAL(10,2) NOT NULL,
  `date_requested` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isAccomplished` TINYINT(4) NOT NULL,
  `tenants_id` INT(11) NOT NULL,
  `employees_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `tenants_id`),
  INDEX `fk_services_tenants_idx` (`tenants_id` ASC) VISIBLE,
  INDEX `fk_services_employees1_idx` (`employees_id` ASC) VISIBLE,
  CONSTRAINT `fk_services_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `aducperesidences`.`employees` (`id`),
  CONSTRAINT `fk_services_tenants`
    FOREIGN KEY (`tenants_id`)
    REFERENCES `aducperesidences`.`tenants` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aducperesidences`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aducperesidences`.`vehicles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `car_model` VARCHAR(45) NOT NULL,
  `manufacturer` VARCHAR(45) NULL DEFAULT NULL,
  `plate_number` VARCHAR(45) NOT NULL,
  `car_seats` INT(11) NOT NULL,
  `tenants_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicles_tenants1_idx` (`tenants_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicles_tenants1`
    FOREIGN KEY (`tenants_id`)
    REFERENCES `aducperesidences`.`tenants` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `aducperesidences` ;

-- -----------------------------------------------------
-- procedure AddPets
-- -----------------------------------------------------

DELIMITER $$
USE `aducperesidences`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddPets`(IN pettype VARCHAR(45), IN breed VARCHAR(45), IN tenant_id INT)
BEGIN
		INSERT INTO `pets` (`pet_type`, `breed`,`tenants_id`)
			VALUES	(pettype, breed, tenant_id);
    END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AddTenant
-- -----------------------------------------------------

DELIMITER $$
USE `aducperesidences`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddTenant`(IN lname VARCHAR(100), IN fname VARCHAR(100), IN midname VARCHAR(100), IN unitno VARCHAR(45), IN phoneno VARCHAR(45), IN email VARCHAR(100), IN provincialadd VARCHAR(100))
BEGIN
		INSERT INTO `AdUCPEResidences`.`tenants` (`lastname`, `firstname`, `middlename`, `unit_no`, `phone_no`, `email_address`, `provincial_address`)
			VALUES(lname,fname,midname,unitno,phoneno,email,provincialadd);
    END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AddVehicles
-- -----------------------------------------------------

DELIMITER $$
USE `aducperesidences`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddVehicles`(IN model VARCHAR(45), IN make VARCHAR(45), IN plate VARCHAR(45), IN seats INT, IN ownerid INT)
BEGIN
		INSERT INTO vehicles (`car_model`, `manufacturer`, `plate_number`, `car_seats`, `tenants_id` )
			VALUES (model, make, plate, seats, ownerid);
    END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure GetPets
-- -----------------------------------------------------

DELIMITER $$
USE `aducperesidences`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetPets`(IN pet_id INT)
BEGIN
		SELECT * FROM `AdUCPEResidences`.`pets` WHERE `AdUCPEResidences`.`pets`.id = pet_id;
    END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure GetTenant
-- -----------------------------------------------------

DELIMITER $$
USE `aducperesidences`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetTenant`(IN tenantid INT)
BEGIN
    IF (tenantid > 0)
    THEN
		(SELECT * FROM tenants where tenants.id = tenantid);
    ELSE	
		(SELECT * FROM tenants);
	END IF;
    END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure AddServiceRequests
-- -----------------------------------------------------

DELIMITER $$
USE `aducperesidences`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddServiceRequests`(IN svctype VARCHAR(45), IN svc_charge VARCHAR(45), IN accomplished TINYINT, IN ownerid INT, IN empid INT)
BEGIN
		INSERT INTO services(`service_type`, `service_charge`, `isAccomplished`, `tenants_id`, `employees_id`)
			VALUES (svctype, svc_charge, accomplished, ownerid, empid);
    END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
